version: '3' 
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    ports:
    - '80:80'
    - '4000:81'
    - '443:443'
    env_file: .env
    volumes:
    - ./data:/data
    - ./letsencrypt:/etc/letsencrypt
  dbnginx:
    image: jc21/mariadb-aria:latest
    container_name: dbnginx
    env_file: .env
    volumes:
    - ./data/mysql:/var/lib/mysql